env:
  browser: true
  es6: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'prettier'
  - 'prettier/@typescript-eslint'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: 'module'
plugins:
  - 'react'
  - 'jest'
  - '@typescript-eslint'
overrides:
  - files:
      - '**/*.test.*' # Remove no-undef rule from jest files.
    rules:
      no-undef: off
rules:
  no-console: off
  react/prop-types: off
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/no-non-null-assertion': off
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/camelcase': off
  '@typescript-eslint/no-empty-interface': off
