proseWrap: always
singleQuote: true
trailingComma: all
jsxBracketSameLine: true
bracketSpacing: false
# overrides:
#   - files: '*.ts'
#     options:
#       printWidth: 120
#   - files: '*.tsx'
#     options:
#       printWidth: 120
